<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MediaBrowser.Model">
      <HintPath>/opt/emby-server/system/MediaBrowser.Model.dll</HintPath>
    </Reference>
    <Reference Include="MediaBrowser.Common">
      <HintPath>/opt/emby-server/system/MediaBrowser.Common.dll</HintPath>
    </Reference>
    <Reference Include="MediaBrowser.Controller">
      <HintPath>/opt/emby-server/system/MediaBrowser.Controller.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
